version: '3.8'  

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Declare both listener names (PLAINTEXT, PLAINTEXT_HOST)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      # Advertise them so that:
      # - Containers use kafka:9092
      # - Host tools use localhost:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CREATE_TOPICS: "adscript.requests:1:1,adscript.tokens:1:1,user.tokens:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    depends_on:
      - zookeeper

    # all services...........
  user-service:
    build:
      context : ./userservice
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - ./userservice/.env
    depends_on:
      - kafka
      - zookeeper


  adscript-service:
    build:
      context : ./adscriptservice
    container_name: adscript-service
    ports:
      - "3002:3002"
    env_file:
      - ./adscriptservice/.env
    depends_on:
      - kafka
      - zookeeper
  
  token-service:
    build:
      context : ./tokenservice
    container_name: token-service
    ports:
      - "3003:3003"
    env_file:
      - ./tokenservice/.env
    depends_on:
      - kafka
      - zookeeper

  payment-service:
    build:
      context : ./paymentservice
    container_name: payment-service
    ports:
      - "3004:3004"
    env_file:
      - ./paymentservice/.env
    depends_on:
      - kafka
      - zookeeper

  api-gateway:
    build:
      context : ./apigatwayservice
    container_name: api-gateway-service
    ports:
      - "3000:3000"
    env_file:
      - ./apigatwayservice/.env
    depends_on:
      - user-service
      - adscript-service
      - token-service
      - payment-service
    

networks:
  default:
    driver: bridge





